a=input('Digite algo:')
print('O tipo primitivo é:',type(a))
print('Só tem espaços?',a.isspace())
print('É numérico?',a.isnumeric())
print('É alfabético?', a.isalpha())
print('É alfanumerico?',a.isalnum())
print('É maiusculo?',a.isupper())
print('É minusculo?',a.islower())
print('É capitalizada?',a.istitle())